In [1]:
from pathlib import Path

pdf_path = Path("../data/raw/MAR FY 2017.pdf")

print(pdf_path)
print(pdf_path.exists())

../data/raw/MAR FY 2017.pdf
True

In [2]:
import importlib.util

packages = ["pdfplumber", "camelot", "tabula"]

for package in packages:
    installed = importlib.util.find_spec(package) is not None
    print(f"{package}: {installed}")

pdfplumber: True
camelot: False
tabula: False

In [3]:
conda install -c conda-forge pdfplumber

2 channel Terms of Service accepted
Retrieving notices: done
Channels:
 - conda-forge
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
    current version: 25.5.1
    latest version: 26.7.2

Please update conda by running

    $ conda update -n base -c defaults conda



# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.

In [4]:
import pdfplumber

with pdfplumber.open(pdf_path) as pdf:
    print("Pages:", len(pdf.pages))
    print(pdf.pages[3].extract_text()[:1500])

Pages: 19
Kansas Medical Assistance Program - Beneficiaries and Expenditures - Fiscal Year 2017 Page 1
Month Beneficiaries** Consumers*** Total Expenditures DHCF Expenditures KDADS Expenditures KDOC Expenditures
Number Avg. Cost Number Avg. Cost Total* Total* Total * Total*
July (5 week) 447,116 $656.17 426,807 $687.39 $293,384,697 $174,870,019 $118,223,966 $290,712
August (4 week) 447,122 $668.64 429,985 $695.29 $298,963,729 $177,359,370 $121,326,470 $277,890
September (4 week) 448,538 $621.33 430,582 $647.24 $278,688,688 $157,190,245 $121,216,824 $281,619
October (5 week) 448,641 $623.33 432,372 $646.79 $279,652,436 $161,183,328 $118,186,464 $282,644
November (4 week) 441,574 $718.75 430,945 $736.48 $317,380,723 $199,975,165 $117,120,884 $284,675
December (5 week) 434,743 $664.83 423,919 $681.81 $289,030,862 $167,040,546 $121,703,856 $286,461
January (4 week) 422,932 $654.89 417,163 $663.95 $276,974,379 $156,889,031 $119,800,013 $285,334
February (4 week) 415,591 $661.00 404,373 $679.34 $274,706,752 $152,224,835 $122,224,276 $257,640
March (5 week) 420,555 $655.65 398,226 $692.41 $275,736,906 $153,899,947 $121,580,539 $256,420
April (4 week) 413,695 $699.03 402,497 $718.47 $289,183,746 $167,276,728 $121,647,231 $259,787
May (4 week) 415,634 $689.23 395,973 $723.46 $286,469,475 $164,372,442 $121,840,157 $256,876
June (5 week) 414,245 $746.03 398,090 $776.31 $309,041,242 $188,625,730 $120,156,107 $259,405
Cumulative Total 5,170,386 $670.98 4,990,932 $695.10 $3,469,213,635 $2,020,907,38

In [5]:
with pdfplumber.open(pdf_path) as pdf:
    page = pdf.pages[3]
    table = page.extract_table()

print(table[:5])

[['Month Beneficiaries** Consumers*** Total Expenditures', 'DHCF Expenditures KDADS Expenditures KDOC Expenditures'], ['Number Avg. Cost Number Avg. Cost Total*\nJuly (5 week) 447,116 $656.17 426,807 $687.39 $293,384,697\nAugust (4 week) 447,122 $668.64 429,985 $695.29 $298,963,729\nSeptember (4 week) 448,538 $621.33 430,582 $647.24 $278,688,688\nOctober (5 week) 448,641 $623.33 432,372 $646.79 $279,652,436\nNovember (4 week) 441,574 $718.75 430,945 $736.48 $317,380,723\nDecember (5 week) 434,743 $664.83 423,919 $681.81 $289,030,862\nJanuary (4 week) 422,932 $654.89 417,163 $663.95 $276,974,379\nFebruary (4 week) 415,591 $661.00 404,373 $679.34 $274,706,752\nMarch (5 week) 420,555 $655.65 398,226 $692.41 $275,736,906\nApril (4 week) 413,695 $699.03 402,497 $718.47 $289,183,746\nMay (4 week) 415,634 $689.23 395,973 $723.46 $286,469,475\nJune (5 week) 414,245 $746.03 398,090 $776.31 $309,041,242', 'Total* Total * Total*\n$174,870,019 $118,223,966 $290,712\n$177,359,370 $121,326,470 $277,890\n$157,190,245 $121,216,824 $281,619\n$161,183,328 $118,186,464 $282,644\n$199,975,165 $117,120,884 $284,675\n$167,040,546 $121,703,856 $286,461\n$156,889,031 $119,800,013 $285,334\n$152,224,835 $122,224,276 $257,640\n$153,899,947 $121,580,539 $256,420\n$167,276,728 $121,647,231 $259,787\n$164,372,442 $121,840,157 $256,876\n$188,625,730 $120,156,107 $259,405'], ['Cumulative Total 5,170,386 $670.98 4,990,932 $695.10 $3,469,213,635', '$2,020,907,386 $1,445,026,787 $3,279,462'], ['Average Per Week\nCurrent Year 99,431 $670.97 95,979 $695.11 $66,715,647\nPrior Year-Same Period 96,354 $657.32 94,748 $668.46 $63,335,359\nPercent Change 3.19% 2.08% 1.30% 3.99% 5.34%', '$38,863,604 $27,788,977 $63,067\n$37,031,968 $26,242,220 $61,172\n4.95% 5.89% 3.10%']]

In [6]:
# Open the FY2017 Medicaid PDF using pdfplumber
with pdfplumber.open(pdf_path) as pdf:
    
    # Access page 4 of the PDF.
    # Python uses zero-based indexing, so index 3 represents the fourth page.
    page = pdf.pages[3]
    
    # Extract all readable text from the page
    text = page.extract_text()

# Split the extracted text into individual lines
# "\n" represents a new line in the extracted PDF text
lines = text.split("\n")

# Loop through each extracted line
for line in lines:
    
    # repr() shows the exact text stored in each line,
    # which helps us inspect the structure before cleaning the data
    print(repr(line))

'Kansas Medical Assistance Program - Beneficiaries and Expenditures - Fiscal Year 2017 Page 1'
'Month Beneficiaries** Consumers*** Total Expenditures DHCF Expenditures KDADS Expenditures KDOC Expenditures'
'Number Avg. Cost Number Avg. Cost Total* Total* Total * Total*'
'July (5 week) 447,116 $656.17 426,807 $687.39 $293,384,697 $174,870,019 $118,223,966 $290,712'
'August (4 week) 447,122 $668.64 429,985 $695.29 $298,963,729 $177,359,370 $121,326,470 $277,890'
'September (4 week) 448,538 $621.33 430,582 $647.24 $278,688,688 $157,190,245 $121,216,824 $281,619'
'October (5 week) 448,641 $623.33 432,372 $646.79 $279,652,436 $161,183,328 $118,186,464 $282,644'
'November (4 week) 441,574 $718.75 430,945 $736.48 $317,380,723 $199,975,165 $117,120,884 $284,675'
'December (5 week) 434,743 $664.83 423,919 $681.81 $289,030,862 $167,040,546 $121,703,856 $286,461'
'January (4 week) 422,932 $654.89 417,163 $663.95 $276,974,379 $156,889,031 $119,800,013 $285,334'
'February (4 week) 415,591 $661.00 404,373 $679.34 $274,706,752 $152,224,835 $122,224,276 $257,640'
'March (5 week) 420,555 $655.65 398,226 $692.41 $275,736,906 $153,899,947 $121,580,539 $256,420'
'April (4 week) 413,695 $699.03 402,497 $718.47 $289,183,746 $167,276,728 $121,647,231 $259,787'
'May (4 week) 415,634 $689.23 395,973 $723.46 $286,469,475 $164,372,442 $121,840,157 $256,876'
'June (5 week) 414,245 $746.03 398,090 $776.31 $309,041,242 $188,625,730 $120,156,107 $259,405'
'Cumulative Total 5,170,386 $670.98 4,990,932 $695.10 $3,469,213,635 $2,020,907,386 $1,445,026,787 $3,279,462'
'Average Per Week'
'Current Year 99,431 $670.97 95,979 $695.11 $66,715,647 $38,863,604 $27,788,977 $63,067'
'Prior Year-Same Period 96,354 $657.32 94,748 $668.46 $63,335,359 $37,031,968 $26,242,220 $61,172'
'Percent Change 3.19% 2.08% 1.30% 3.99% 5.34% 4.95% 5.89% 3.10%'
'* Total monthly expenditures include non-client specific expenditures, but do not include certified match.'
'**Beneficiaries are eligible for services as of month end for that month. The Beneficiaries do not all use service during the given month but they are eligible in that month.'
'NOTE: Drug rebate amounts are not deducted from KDHE/DHCF Expenditures.'
'NOTE: The Beneficiary numbers include Fee-for-Service and Managed Care enrollees.'
'NOTE: KanCare capitation payments are paid in arrears for the month of beneficiary eligibility. (for example: Capitation payments for beneficiaries eligible in the month of January are paid out in the month of February).'

In [7]:
# Import Python's regular expression module.
# We will use regex to recognize and extract values from each monthly line.
import re

# Define the 12 month names we expect to find in the report.
months = [
    "July", "August", "September", "October",
    "November", "December", "January", "February",
    "March", "April", "May", "June"
]

# Create an empty list where we will store each extracted monthly record.
monthly_records = []

# Loop through every line extracted from the PDF.
for line in lines:
    
    # Check whether the line begins with one of our month names.
    # Only monthly data rows should pass this test.
    if any(line.startswith(month) for month in months):
        
        # Use a regular expression to capture:
        # 1. Month name
        # 2. Number of weeks shown in parentheses
        # 3. Beneficiaries
        # 4. Beneficiary average cost
        # 5. Consumers
        # 6. Consumer average cost
        # 7. Total expenditures
        pattern = (
            r"^(\w+) "
            r"\((\d+) week\) "
            r"([\d,]+) "
            r"\$([\d,.]+) "
            r"([\d,]+) "
            r"\$([\d,.]+) "
            r"\$([\d,]+)"
        )

        match = re.search(pattern, line)

        # If the line matches the expected structure,
        # extract the values and save them as a dictionary.
        if match:
            record = {
                "fiscal_year": 2017,
                "month": match.group(1),
                "weeks": int(match.group(2)),
                "beneficiaries": int(match.group(3).replace(",", "")),
                "beneficiary_avg_cost": float(match.group(4).replace(",", "")),
                "consumers": int(match.group(5).replace(",", "")),
                "consumer_avg_cost": float(match.group(6).replace(",", "")),
                "total_expenditures": int(match.group(7).replace(",", ""))
            }

            monthly_records.append(record)

# Display the extracted records so we can verify the parser worked correctly.
monthly_records

[{'fiscal_year': 2017,
  'month': 'July',
  'weeks': 5,
  'beneficiaries': 447116,
  'beneficiary_avg_cost': 656.17,
  'consumers': 426807,
  'consumer_avg_cost': 687.39,
  'total_expenditures': 293384697},
 {'fiscal_year': 2017,
  'month': 'August',
  'weeks': 4,
  'beneficiaries': 447122,
  'beneficiary_avg_cost': 668.64,
  'consumers': 429985,
  'consumer_avg_cost': 695.29,
  'total_expenditures': 298963729},
 {'fiscal_year': 2017,
  'month': 'September',
  'weeks': 4,
  'beneficiaries': 448538,
  'beneficiary_avg_cost': 621.33,
  'consumers': 430582,
  'consumer_avg_cost': 647.24,
  'total_expenditures': 278688688},
 {'fiscal_year': 2017,
  'month': 'October',
  'weeks': 5,
  'beneficiaries': 448641,
  'beneficiary_avg_cost': 623.33,
  'consumers': 432372,
  'consumer_avg_cost': 646.79,
  'total_expenditures': 279652436},
 {'fiscal_year': 2017,
  'month': 'November',
  'weeks': 4,
  'beneficiaries': 441574,
  'beneficiary_avg_cost': 718.75,
  'consumers': 430945,
  'consumer_avg_cost': 736.48,
  'total_expenditures': 317380723},
 {'fiscal_year': 2017,
  'month': 'December',
  'weeks': 5,
  'beneficiaries': 434743,
  'beneficiary_avg_cost': 664.83,
  'consumers': 423919,
  'consumer_avg_cost': 681.81,
  'total_expenditures': 289030862},
 {'fiscal_year': 2017,
  'month': 'January',
  'weeks': 4,
  'beneficiaries': 422932,
  'beneficiary_avg_cost': 654.89,
  'consumers': 417163,
  'consumer_avg_cost': 663.95,
  'total_expenditures': 276974379},
 {'fiscal_year': 2017,
  'month': 'February',
  'weeks': 4,
  'beneficiaries': 415591,
  'beneficiary_avg_cost': 661.0,
  'consumers': 404373,
  'consumer_avg_cost': 679.34,
  'total_expenditures': 274706752},
 {'fiscal_year': 2017,
  'month': 'March',
  'weeks': 5,
  'beneficiaries': 420555,
  'beneficiary_avg_cost': 655.65,
  'consumers': 398226,
  'consumer_avg_cost': 692.41,
  'total_expenditures': 275736906},
 {'fiscal_year': 2017,
  'month': 'April',
  'weeks': 4,
  'beneficiaries': 413695,
  'beneficiary_avg_cost': 699.03,
  'consumers': 402497,
  'consumer_avg_cost': 718.47,
  'total_expenditures': 289183746},
 {'fiscal_year': 2017,
  'month': 'May',
  'weeks': 4,
  'beneficiaries': 415634,
  'beneficiary_avg_cost': 689.23,
  'consumers': 395973,
  'consumer_avg_cost': 723.46,
  'total_expenditures': 286469475},
 {'fiscal_year': 2017,
  'month': 'June',
  'weeks': 5,
  'beneficiaries': 414245,
  'beneficiary_avg_cost': 746.03,
  'consumers': 398090,
  'consumer_avg_cost': 776.31,
  'total_expenditures': 309041242}]

In [8]:
# Import pandas for working with structured tabular data
import pandas as pd

# Convert the list of monthly dictionaries into a pandas DataFrame.
# Each dictionary becomes one row and each dictionary key becomes a column.
fy2017_df = pd.DataFrame(monthly_records)

# Display the DataFrame so we can visually inspect the extracted data.
fy2017_df

,fiscal_year,month,weeks,beneficiaries,beneficiary_avg_cost,consumers,consumer_avg_cost,total_expenditures
0,2017,July,5,447116,656.17,426807,687.39,293384697
1,2017,August,4,447122,668.64,429985,695.29,298963729
2,2017,September,4,448538,621.33,430582,647.24,278688688
3,2017,October,5,448641,623.33,432372,646.79,279652436
4,2017,November,4,441574,718.75,430945,736.48,317380723
5,2017,December,5,434743,664.83,423919,681.81,289030862
6,2017,January,4,422932,654.89,417163,663.95,276974379
7,2017,February,4,415591,661.00,404373,679.34,274706752
8,2017,March,5,420555,655.65,398226,692.41,275736906
9,2017,April,4,413695,699.03,402497,718.47,289183746
10,2017,May,4,415634,689.23,395973,723.46,286469475
11,2017,June,5,414245,746.03,398090,776.31,309041242

In [9]:
# Check the dimensions of the extracted dataset.
# We expect exactly 12 rows because a fiscal year contains 12 months.
print("Rows and columns:", fy2017_df.shape)

# Check whether every expected fiscal-year month appears exactly once.
print("\nMonths extracted:")
print(fy2017_df["month"].tolist())

# Check for missing values in each column.
# A result of 0 means that column has no missing data.
print("\nMissing values:")
print(fy2017_df.isna().sum())

# Calculate annual total expenditures from the 12 extracted monthly values.
calculated_expenditures = fy2017_df["total_expenditures"].sum()

print("\nCalculated FY2017 expenditures:")
print(f"${calculated_expenditures:,.0f}")

# Compare our calculated total against the cumulative total printed
# in the original FY2017 Kansas Medical Assistance report.
reported_expenditures = 3_469_213_635

print("\nReported FY2017 expenditures:")
print(f"${reported_expenditures:,.0f}")

# Confirm whether our extracted monthly values reproduce
# the official annual expenditure total exactly.
print("\nExpenditure validation passed:")
print(calculated_expenditures == reported_expenditures)

Rows and columns: (12, 8)

Months extracted:
['July', 'August', 'September', 'October', 'November', 'December', 'January', 'February', 'March', 'April', 'May', 'June']

Missing values:
fiscal_year             0
month                   0
weeks                   0
beneficiaries           0
beneficiary_avg_cost    0
consumers               0
consumer_avg_cost       0
total_expenditures      0
dtype: int64

Calculated FY2017 expenditures:
$3,469,213,635

Reported FY2017 expenditures:
$3,469,213,635

Expenditure validation passed:
True

In [10]:
# Add the beneficiary counts from all 12 months.
# This should reproduce the cumulative beneficiary total
# printed in the FY2017 report.
calculated_beneficiary_total = fy2017_df["beneficiaries"].sum()

# Official cumulative beneficiary total shown in the FY2017 report.
reported_beneficiary_total = 5_170_386

print("Calculated cumulative beneficiaries:")
print(f"{calculated_beneficiary_total:,}")

print("\nReported cumulative beneficiaries:")
print(f"{reported_beneficiary_total:,}")

# Confirm that our extracted monthly beneficiary counts
# reproduce the report's cumulative total exactly.
print("\nBeneficiary validation passed:")
print(calculated_beneficiary_total == reported_beneficiary_total)


# Calculate the average monthly beneficiary count.
# This is more useful for our annual trend analysis because
# it represents the typical monthly enrollment level during FY2017.
average_monthly_beneficiaries = fy2017_df["beneficiaries"].mean()

print("\nAverage monthly beneficiaries:")
print(f"{average_monthly_beneficiaries:,.0f}")

Calculated cumulative beneficiaries:
5,170,386

Reported cumulative beneficiaries:
5,170,386

Beneficiary validation passed:
True

Average monthly beneficiaries:
430,866

In [11]:
# Search every page in the FY2017 PDF for the
# "Beneficiaries and Expenditures" section.
# This avoids relying on a fixed page number that may change
# between fiscal-year reports.

with pdfplumber.open(pdf_path) as pdf:

    for page_number, page in enumerate(pdf.pages):

        # Extract text from the current page.
        # If no text is found, use an empty string instead.
        page_text = page.extract_text() or ""

        # Check whether this is the page containing
        # the Beneficiaries and Expenditures table.
        if "Beneficiaries and Expenditures" in page_text:

            # Add 1 because Python starts counting pages at 0,
            # while humans normally start counting at 1.
            print("Found on PDF page:", page_number + 1)

            # Show the first line so we can verify
            # that Python located the correct section.
            print(page_text.split("\n")[0])

Found on PDF page: 4
Kansas Medical Assistance Program - Beneficiaries and Expenditures - Fiscal Year 2017 Page 1

In [12]:
# Build the path to the FY2018 Medicaid report.
# We are using the same relative path structure as FY2017.
fy2018_path = Path("../data/raw/MAR FY 2018.pdf")

# Confirm that Python can find the FY2018 PDF.
print("FY2018 file exists:", fy2018_path.exists())


# Search every page in the FY2018 report for the
# "Beneficiaries and Expenditures" section.
with pdfplumber.open(fy2018_path) as pdf:

    for page_number, page in enumerate(pdf.pages):

        # Extract text from the current page.
        # If the page has no readable text, use an empty string.
        page_text = page.extract_text() or ""

        # Look for the section title we used successfully in FY2017.
        if "Beneficiaries and Expenditures" in page_text:

            # Add 1 because Python page indexes start at 0.
            print("Found on PDF page:", page_number + 1)

            # Print the first line to confirm we found the correct section.
            print(page_text.split("\n")[0])

FY2018 file exists: True
Found on PDF page: 4
Kansas Medical Assistance Program - Beneficiaries and Expenditures - Fiscal Year 2018 Page 1

In [13]:
# Create a reusable function that extracts the monthly
# "Beneficiaries and Expenditures" data from one fiscal-year PDF.

def extract_medicaid_year(pdf_path, fiscal_year):
    
    # Open the PDF file.
    with pdfplumber.open(pdf_path) as pdf:
        
        # Start with no matching page found.
        target_page_text = None
        
        # Search every page for the section title.
        for page in pdf.pages:
            
            # Extract text from the current page.
            # Use an empty string if the page contains no readable text.
            page_text = page.extract_text() or ""
            
            # Identify the page containing the monthly
            # Beneficiaries and Expenditures table.
            if "Beneficiaries and Expenditures" in page_text:
                target_page_text = page_text
                break

    # Stop with an error if the expected section was not found.
    # This protects us from silently extracting incorrect data.
    if target_page_text is None:
        raise ValueError(
            f"Beneficiaries and Expenditures section not found for FY{fiscal_year}"
        )

    # Split the page into individual text lines.
    lines = target_page_text.split("\n")

    # Define the month names expected in each fiscal-year report.
    months = [
        "July", "August", "September", "October",
        "November", "December", "January", "February",
        "March", "April", "May", "June"
    ]

    # Create an empty list to store the extracted monthly records.
    monthly_records = []

    # Define the structure expected for each monthly row.
    # The pattern captures:
    # month, number of weeks, beneficiaries, beneficiary average cost,
    # consumers, consumer average cost, and total expenditures.
    pattern = (
        r"^(\w+) "
        r"\((\d+) week\) "
        r"([\d,]+) "
        r"\$([\d,.]+) "
        r"([\d,]+) "
        r"\$([\d,.]+) "
        r"\$([\d,]+)"
    )

    # Examine each line from the selected page.
    for line in lines:

        # Only process rows that begin with a month name.
        if any(line.startswith(month) for month in months):

            # Try to match the line against the expected monthly pattern.
            match = re.search(pattern, line)

            # If the pattern matches, convert the text values
            # into clean numeric fields.
            if match:
                record = {
                    "fiscal_year": fiscal_year,
                    "month": match.group(1),
                    "weeks": int(match.group(2)),
                    "beneficiaries": int(match.group(3).replace(",", "")),
                    "beneficiary_avg_cost": float(match.group(4).replace(",", "")),
                    "consumers": int(match.group(5).replace(",", "")),
                    "consumer_avg_cost": float(match.group(6).replace(",", "")),
                    "total_expenditures": int(match.group(7).replace(",", ""))
                }

                monthly_records.append(record)

    # Convert the extracted monthly records into a pandas DataFrame.
    df = pd.DataFrame(monthly_records)

    # Return the completed fiscal-year dataset.
    return df

In [14]:
# Run the reusable extraction function on the FY2018 report.
fy2018_df = extract_medicaid_year(
    Path("../data/raw/MAR FY 2018.pdf"),
    2018
)

# Display the extracted FY2018 data.
fy2018_df

,fiscal_year,month,weeks,beneficiaries,beneficiary_avg_cost,consumers,consumer_avg_cost,total_expenditures
0,2018,July,4,414235,685.33,396537,715.92,283888198
1,2018,August,5,410631,680.97,406752,687.47,279628172
2,2018,September,4,407518,710.18,392960,736.49,289411460
3,2018,October,4,411626,683.49,390815,719.89,281342938
4,2018,November,5,414099,740.69,405271,756.82,306717772
5,2018,December,4,415954,750.08,394526,790.82,311997206
6,2018,January,4,421065,686.29,398508,725.14,288974090
7,2018,February,4,423574,776.89,400913,820.81,329072174
8,2018,March,5,423335,740.16,408086,767.81,313334465
9,2018,April,4,420740,746.22,406072,773.17,313963806
10,2018,May,5,418249,781.37,412297,792.65,326807276
11,2018,June,4,416687,820.09,398787,856.90,341721521

In [15]:
# Create a reusable validation function for one fiscal-year DataFrame.
# This checks the basic structure of the extracted data before we trust it.

def validate_medicaid_year(df, fiscal_year):
    
    # Expected fiscal-year month order.
    expected_months = [
        "July", "August", "September", "October",
        "November", "December", "January", "February",
        "March", "April", "May", "June"
    ]
    
    # Check 1: confirm that exactly 12 monthly rows were extracted.
    row_check = len(df) == 12
    
    # Check 2: confirm that the months appear in the expected order.
    month_check = df["month"].tolist() == expected_months
    
    # Check 3: confirm that no values are missing.
    missing_check = df.isna().sum().sum() == 0
    
    # Display the results clearly.
    print(f"FY{fiscal_year} validation")
    print("-" * 25)
    print("12 rows:", row_check)
    print("Correct months:", month_check)
    print("No missing values:", missing_check)
    
    # Calculate annual totals that we can later compare
    # against the official cumulative totals in the report.
    annual_expenditures = df["total_expenditures"].sum()
    average_beneficiaries = df["beneficiaries"].mean()
    
    print(f"\nAnnual expenditures: ${annual_expenditures:,.0f}")
    print(f"Average monthly beneficiaries: {average_beneficiaries:,.0f}")

In [16]:
# Validate the FY2018 dataset using the reusable function.
validate_medicaid_year(fy2018_df, 2018)

FY2018 validation
-------------------------
12 rows: True
Correct months: True
No missing values: True

Annual expenditures: $3,666,859,078
Average monthly beneficiaries: 416,476

In [17]:
# Create an empty list to store each fiscal year's DataFrame.
all_years = []

# Loop through fiscal years 2017 through 2026.
for fiscal_year in range(2017, 2027):
    
    # Build the file path for the current fiscal-year PDF.
    pdf_path = Path(f"../data/raw/MAR FY {fiscal_year}.pdf")
    
    # Extract the monthly Medicaid data using our reusable function.
    yearly_df = extract_medicaid_year(pdf_path, fiscal_year)
    
    # Store the extracted DataFrame in our list.
    all_years.append(yearly_df)

# Combine all 10 fiscal-year DataFrames into one dataset.
# ignore_index=True creates a clean row index from 0 onward.
medicaid_monthly_df = pd.concat(all_years, ignore_index=True)

# Display the combined dataset.
medicaid_monthly_df

,fiscal_year,month,weeks,beneficiaries,beneficiary_avg_cost,consumers,consumer_avg_cost,total_expenditures
0,2017,July,5,447116,656.17,426807,687.39,293384697
1,2017,August,4,447122,668.64,429985,695.29,298963729
2,2017,September,4,448538,621.33,430582,647.24,278688688
3,2017,October,5,448641,623.33,432372,646.79,279652436
4,2017,November,4,441574,718.75,430945,736.48,317380723
...,...,...,...,...,...,...,...,...
115,2026,February,4,426169,1173.00,413021,1211.00,500053355
116,2026,March,5,425441,1133.00,415794,1159.00,482111148
117,2026,April,4,424654,1250.00,416436,1275.00,530804231
118,2026,May,5,424527,1125.00,406832,1174.00,477662271
119,2026,June,4,422460,1166.00,402719,1223.00,492427988

In [18]:
# Check the total number of rows and columns.
print("Rows and columns:", medicaid_monthly_df.shape)

# Count how many monthly records were extracted for each fiscal year.
print("\nRows per fiscal year:")
print(medicaid_monthly_df.groupby("fiscal_year").size())

Rows and columns: (120, 8)

Rows per fiscal year:
fiscal_year
2017    12
2018    12
2019    12
2020    12
2021    12
2022    12
2023    12
2024    12
2025    12
2026    12
dtype: int64

In [19]:
# ---------------------------------------------------------
# CREATE ANNUAL MEDICAID SUMMARY
# ---------------------------------------------------------

# Aggregate the 120 monthly records into one row per fiscal year.
#
# We use:
# - mean() for beneficiaries to calculate average monthly enrollment
# - mean() for consumers to calculate average monthly consumers
# - sum() for beneficiaries to calculate total beneficiary-months
# - sum() for expenditures to calculate total annual spending
annual_summary = (
    medicaid_monthly_df
    .groupby("fiscal_year")
    .agg(
        avg_monthly_beneficiaries=("beneficiaries", "mean"),
        avg_monthly_consumers=("consumers", "mean"),
        beneficiary_months=("beneficiaries", "sum"),
        total_expenditures=("total_expenditures", "sum")
    )
    .reset_index()
)


# Calculate expenditure per beneficiary-month.
#
# A beneficiary-month represents one beneficiary enrolled for one month.
# Dividing annual expenditures by total beneficiary-months gives us
# a normalized measure of spending relative to enrollment.
#
# This is a spending-intensity measure. It should not be interpreted
# as an individual's medical cost or as a measure of program efficiency.
annual_summary["expenditure_per_beneficiary_month"] = (
    annual_summary["total_expenditures"]
    / annual_summary["beneficiary_months"]
)


# Calculate year-over-year percentage change in average monthly beneficiaries.
# pct_change() compares each fiscal year with the previous fiscal year.
annual_summary["beneficiary_yoy_pct"] = (
    annual_summary["avg_monthly_beneficiaries"]
    .pct_change()
    * 100
)


# Calculate year-over-year percentage change in total expenditures.
annual_summary["expenditure_yoy_pct"] = (
    annual_summary["total_expenditures"]
    .pct_change()
    * 100
)


# Round average monthly counts to whole beneficiaries/consumers.
annual_summary["avg_monthly_beneficiaries"] = (
    annual_summary["avg_monthly_beneficiaries"].round(0)
)

annual_summary["avg_monthly_consumers"] = (
    annual_summary["avg_monthly_consumers"].round(0)
)


# Round expenditure per beneficiary-month to cents.
annual_summary["expenditure_per_beneficiary_month"] = (
    annual_summary["expenditure_per_beneficiary_month"].round(2)
)


# Round year-over-year percentage changes to two decimal places.
annual_summary["beneficiary_yoy_pct"] = (
    annual_summary["beneficiary_yoy_pct"].round(2)
)

annual_summary["expenditure_yoy_pct"] = (
    annual_summary["expenditure_yoy_pct"].round(2)
)


# Display the completed annual summary for validation.
annual_summary

,fiscal_year,avg_monthly_beneficiaries,avg_monthly_consumers,beneficiary_months,total_expenditures,expenditure_per_beneficiary_month,beneficiary_yoy_pct,expenditure_yoy_pct
0,2017,430866.0,415911.0,5170386,3469213635,670.98,NaN,NaN
1,2018,416476.0,400960.0,4997713,3666859078,733.71,-3.34,5.70
2,2019,410579.0,395514.0,4926945,3936843520,799.04,-1.42,7.36
3,2020,408138.0,392586.0,4897652,4189753837,855.46,-0.59,6.42
4,2021,461090.0,441092.0,5533082,4426412757,799.99,12.97,5.65
5,2022,502118.0,482941.0,6025420,4859228793,806.45,8.90,9.78
6,2023,529075.0,509802.0,6348900,5429434410,855.18,5.37,11.73
7,2024,467440.0,446299.0,5609284,5510409877,982.37,-11.65,1.49
8,2025,439901.0,423028.0,5278814,5955636294,1128.21,-5.89,8.08
9,2026,427603.0,410678.0,5131241,5848965317,1139.87,-2.80,-1.79

In [20]:
# ---------------------------------------------------------
# FINAL QUALITY CHECKS FOR THE 10-YEAR MONTHLY DATASET
# ---------------------------------------------------------

# Check 1: Look for duplicate fiscal year + month combinations.
# Each fiscal year should contain exactly one record for each month.
duplicate_rows = medicaid_monthly_df.duplicated(
    subset=["fiscal_year", "month"]
).sum()

print("Duplicate fiscal year/month rows:", duplicate_rows)


# Check 2: Look for missing values anywhere in the dataset.
missing_values = medicaid_monthly_df.isna().sum().sum()

print("Total missing values:", missing_values)


# Check 3: Check for zero or negative beneficiary counts.
# These would be suspicious for monthly Medicaid enrollment data.
invalid_beneficiaries = (
    medicaid_monthly_df["beneficiaries"] <= 0
).sum()

print("Invalid beneficiary values:", invalid_beneficiaries)


# Check 4: Check for zero or negative total expenditures.
# Unexpected values here would require us to return to the source PDF.
invalid_expenditures = (
    medicaid_monthly_df["total_expenditures"] <= 0
).sum()

print("Invalid expenditure values:", invalid_expenditures)


# Check 5: Determine whether consumers ever exceed beneficiaries.
# Beneficiaries represent eligible individuals, while consumers
# represent individuals associated with paid services.
consumer_over_beneficiary = (
    medicaid_monthly_df["consumers"]
    > medicaid_monthly_df["beneficiaries"]
).sum()

print(
    "Months where consumers exceed beneficiaries:",
    consumer_over_beneficiary
)


# Check 6: Confirm the complete fiscal-year range.
print(
    "Fiscal year range:",
    medicaid_monthly_df["fiscal_year"].min(),
    "to",
    medicaid_monthly_df["fiscal_year"].max()
)


# Check 7: Confirm the final number of observations.
print("Total monthly observations:", len(medicaid_monthly_df))

Duplicate fiscal year/month rows: 0
Total missing values: 0
Invalid beneficiary values: 0
Invalid expenditure values: 0
Months where consumers exceed beneficiaries: 2
Fiscal year range: 2017 to 2026
Total monthly observations: 120

In [21]:
# ---------------------------------------------------------
# REVIEW MONTHS WHERE CONSUMERS EXCEED BENEFICIARIES
# ---------------------------------------------------------

# Filter the monthly dataset to only the observations
# where the reported consumer count is greater than
# the reported beneficiary count.
consumer_exceeds_beneficiary = medicaid_monthly_df[
    medicaid_monthly_df["consumers"]
    > medicaid_monthly_df["beneficiaries"]
].copy()

# Calculate the difference so we can see
# how large the discrepancy is in each month.
consumer_exceeds_beneficiary["difference"] = (
    consumer_exceeds_beneficiary["consumers"]
    - consumer_exceeds_beneficiary["beneficiaries"]
)

# Display the fiscal year, month, and both counts
# for manual validation against the source reports.
consumer_exceeds_beneficiary[
    [
        "fiscal_year",
        "month",
        "beneficiaries",
        "consumers",
        "difference"
    ]
]

    fiscal_year    month  beneficiaries  consumers  difference
37         2020   August         399495     409361        9866
39         2020  October         402663     411253        8590

In [22]:
# ---------------------------------------------------------
# SAVE CLEAN PROCESSED DATASETS
# ---------------------------------------------------------

# Define the folder where cleaned datasets will be stored.
# Keeping processed data separate from raw PDFs preserves
# the original source files and makes the workflow reproducible.
processed_folder = Path("../data/processed")

# Create the folder if it does not already exist.
# exist_ok=True prevents an error if the folder is already there.
processed_folder.mkdir(parents=True, exist_ok=True)


# Save the complete 120-row monthly dataset.
# index=False prevents pandas from writing the DataFrame's
# row numbers as an unnecessary CSV column.
medicaid_monthly_df.to_csv(
    processed_folder / "kansas_medicaid_monthly_2017_2026.csv",
    index=False
)


# Save the 10-row annual summary dataset.
# This will be useful for annual trend analysis and visualization.
annual_summary.to_csv(
    processed_folder / "kansas_medicaid_annual_2017_2026.csv",
    index=False
)


# Confirm that both files were successfully created.
print(
    "Monthly file saved:",
    (processed_folder / "kansas_medicaid_monthly_2017_2026.csv").exists()
)

print(
    "Annual file saved:",
    (processed_folder / "kansas_medicaid_annual_2017_2026.csv").exists()
)

Monthly file saved: True
Annual file saved: True

In [23]:
# ---------------------------------------------------------
# INSPECT FY2026 EXPENDITURES BY CATEGORY OF SERVICE
# ---------------------------------------------------------

# Define the path to the FY2026 Medicaid report.
fy2026_path = Path("../data/raw/MAR FY 2026.pdf")

# Open the FY2026 PDF.
with pdfplumber.open(fy2026_path) as pdf:

    # Search every page in the report.
    for page_number, page in enumerate(pdf.pages):

        # Extract readable text from the current page.
        # If no text is available, use an empty string.
        page_text = page.extract_text() or ""

        # Find pages containing the Category of Service section.
        if "Expenditures by Category of Service" in page_text:

            # Print a separator so multiple matching pages
            # are easy to distinguish in the output.
            print("\n" + "=" * 70)

            # Display the physical PDF page number.
            print("Found on PDF page:", page_number + 1)

            print("=" * 70)

            # Display the page contents so we can compare
            # the FY2026 structure with FY2017.
            print(page_text)

======================================================================
Found on PDF page: 10
======================================================================
Kansas Medical Assistance Program - Fiscal Year 2026 Page 7
Expenditures by Category of Service
(July 2025 - June 2026) Monthly State
July August September October November December January February March April May June Total Average Funds
Inpatient $2,866,693 $4,441,086 $3,113,792 $4,663,683 $1,837,883 $2,562,288 $1,994,778 $3,307,636 $2,873,248 $2,827,387 $2,243,323 $2,902,166 $35,633,962 $2,969,497 $13,907,935
Inpatient Hospital-DSH Adjustments $33,830,313 $0 $0 $0 $0 $0 $0 $0 $0 $0 $0 $0 $33,830,313 $33,830,313 $13,203,971
Mental Health Facilities-DSH Adjustments $8,789,169 $0 $0 $0 $0 $0 $0 $0 $0 $0 $0 $0 $8,789,169 $8,789,169 $3,430,413
Outpatient $379,351 $379,572 $309,371 $461,738 $282,051 $243,988 $285,231 $285,721 $256,580 $366,754 $282,747 $273,681 $3,806,784 $317,232 $1,485,788
Pharmacy $2,173,637 $2,879,059 $1,455,878 $2,300,031 $1,668,310 $1,733,144 $3,397,927 $2,948,258 $2,379,408 $3,001,190 $2,167,295 $2,034,857 $28,138,994 $2,344,916 $10,982,649
Professional Services $1,996,020 $1,232,217 $2,123,771 $4,020,423 $2,990,797 $3,269,008 $3,228,903 $2,826,000 $3,983,253 $4,353,641 $2,781,870 $18,740,956 $51,546,859 $4,295,572 $20,118,739
Medicare Buy-In $14,213,988 $14,222,215 $14,430,388 $14,343,357 $14,162,926 $14,283,077 $15,293,228 $15,553,965 $15,478,005 $15,669,717 $15,520,947 $15,657,516 $178,829,330 $14,902,444 $69,797,087
HCBS Waivers (Fee for Service Only) $0 $0 $0 $4,267 $4,787 $11,226 $426 $0 $4,592 $1,023 $0 $0 $26,322 $4,387 $10,273
Targeted Case Management $136,510 $110,282 $105,418 $129,811 $115,470 $101,275 $107,392 $108,356 $117,203 $122,590 $110,238 $110,811 $1,375,357 $114,613 $536,802
Long Term Care $5,513,677 $6,871,329 $3,210,463 $15,116,798 $6,913,793 $6,334,662 $11,646,486 $6,204,691 $6,523,610 $7,095,687 $6,642,158 $6,695,853 $88,769,206 $7,397,434 $34,646,621
Managed Care $463,895,737 $441,362,490 $435,758,069 $435,576,476 $443,597,190 $437,130,521 $448,443,846 $468,611,806 $450,272,271 $497,101,331 $447,659,207 $445,773,988 $5,415,182,932 $451,265,244 $2,113,545,898
KDHE (KanCare) $216,466,392 $202,787,500 $201,404,515 $200,453,711 $202,348,771 $198,323,569 $203,168,203 $204,819,588 $207,203,972 $234,102,031 $206,008,163 $177,237,439 $2,454,323,854 $204,526,988 $957,922,600
KDADs (KanCare) $264,261,689 $251,666,343 $250,636,871 $250,805,137 $253,656,314 $253,365,023 $261,258,696 $257,345,423 $259,570,363 $288,108,676 $258,657,040 $257,406,890 $3,106,738,464 $258,894,872 $1,212,560,022
All Other Medical $336,804 $382,274 $195,332 $326,871 $184,275 $193,383 $229,695 $206,923 $222,976 $264,911 $254,486 $238,160 $3,036,089 $253,007 $1,184,985
Total Expenditures $534,131,899 $471,880,524 $460,702,481 $476,943,454 $471,757,482 $465,862,572 $484,627,912 $500,053,355 $482,111,148 $530,804,231 $477,662,271 $492,427,988 $5,848,965,316 $487,413,776 $2,282,851,163
Consumers* by Category of Service
(July 2025 - June 2026) Monthly
July August September October November December January February March April May June Average
Inpatient 464 415 428 548 357 349 354 370 429 464 399 310 407
Outpatient 3,094 2,939 2,508 3,044 2,433 2,327 2,706 2,410 2,475 3,168 2,446 2,436 2,666
Pharmacy 1,102 982 962 1,118 970 961 1,407 1,369 1,224 1,281 1,103 1,044 1,127
Professional Services 12,495 11,609 17,469 23,011 19,586 23,391 23,886 20,065 24,788 26,839 20,175 17,509 20,069
Medicare Buy-In 70,026 70,110 70,123 69,787 69,730 69,971 69,901 70,152 70,213 70,470 70,682 70,945 70,176
HCBS Waivers (Fee for Service Only) 0 0 0 2 1 1 1 0 3 2 0 0 2
Targeted Case Management 1,913 1,746 1,803 1,947 1,836 1,781 1,805 1,873 1,884 2,023 1,875 1,774 1,855
Long Term Care 616 595 458 781 729 723 738 670 719 738 687 712 681
Managed Care 431,679 367,426 368,455 366,248 368,583 366,390 365,813 487,340 477,906 453,349 368,171 365,264 398,885
All Other Medical 2,260 2,637 2,058 2,267 2,002 1,687 2,425 1,911 1,731 2,216 1,682 1,771 2,054
Total Consumers 410,319 405,319 408,975 413,631 411,551 410,773 412,760 413,021 415,794 416,436 406,832 402,719 410,678
*Consumers are those for whom a payment was made during the month, including Managed Care Capitation payments. They are determined by the date of payment. Managed Care enrollees may or may not use services in any
given month.
State Funds are calculated utilizing a blended FMAP and are not actual State Funds expended

In [24]:
# ---------------------------------------------------------
# CHECK CATEGORY-OF-SERVICE REPORT STRUCTURE BY YEAR
# ---------------------------------------------------------

# Loop through every fiscal-year report.
for fiscal_year in range(2017, 2027):

    # Build the path to the report for the current fiscal year.
    pdf_path = Path(
        f"../data/raw/MAR FY {fiscal_year}.pdf"
    )

    # Store the PDF pages containing the Category of Service section.
    category_pages = []

    # Open the current report.
    with pdfplumber.open(pdf_path) as pdf:

        # Search every page.
        for page_number, page in enumerate(pdf.pages):

            # Extract readable text from the page.
            page_text = page.extract_text() or ""

            # Identify pages containing the Category of Service section.
            if "Expenditures by Category of Service" in page_text:

                # Store the human-readable PDF page number.
                category_pages.append(page_number + 1)

    # Display the result for the current fiscal year.
    print(
        f"FY{fiscal_year}: "
        f"{len(category_pages)} page(s) → {category_pages}"
    )

FY2017: 3 page(s) → [15, 16, 17]
FY2018: 1 page(s) → [10]
FY2019: 1 page(s) → [10]
FY2020: 1 page(s) → [10]
FY2021: 1 page(s) → [10]
FY2022: 1 page(s) → [10]
FY2023: 1 page(s) → [10]
FY2024: 1 page(s) → [10]
FY2025: 1 page(s) → [10]
FY2026: 1 page(s) → [10]

In [25]:
# ---------------------------------------------------------
# COMPARE CATEGORY NAMES ACROSS FY2018-FY2026
# ---------------------------------------------------------

import re

# Loop through the reports that use the newer one-page format.
for fiscal_year in range(2018, 2027):

    # Build the path to the current fiscal-year report.
    pdf_path = Path(
        f"../data/raw/MAR FY {fiscal_year}.pdf"
    )

    print(f"\n{'=' * 60}")
    print(f"FY{fiscal_year}")
    print("=" * 60)

    with pdfplumber.open(pdf_path) as pdf:

        # Page 10 in the PDF corresponds to Python index 9.
        page_text = pdf.pages[9].extract_text() or ""

        # Examine the page one line at a time.
        for line in page_text.splitlines():

            # Category rows contain dollar amounts.
            # Find the position of the first dollar amount.
            match = re.search(r"-?\$", line)

            if match:

                # Everything before the first dollar amount
                # should normally be the category label.
                category = line[:match.start()].strip()

                # Skip blank labels.
                if category:
                    print(category)

============================================================
FY2018
============================================================
Inpatient
Inpatient Hospital-DSH Adjustments
Mental Health Facilities-DSH Adjustment
Outpatient
Pharmacy
Professional Services
Medicare Buy-In
HCBS Waivers
Targeted Case Management
Long Term Care
Managed Care
KDHE (KanCare)
KDADs (KanCare)
All Other Medical
Total Expenditures

============================================================
FY2019
============================================================
Inpatient
Inpatient Hospital-DSH Adjustments
Mental Health Facilities-DSH Adjustments
Outpatient
Pharmacy
Professional Services
Medicare Buy-In
HCBS Waivers
Targeted Case Management
Long Term Care
Managed Care
KDHE (KanCare)
KDADs (KanCare)
All Other Medical
Total Expenditures

============================================================
FY2020
============================================================
Inpatient
Inpatient Hospital-DSH Adjustments
Mental Health Facilities-DSH Adjustments
Outpatient
Pharmacy
Professional Services
Medicare Buy-In
HCBS Waivers
Targeted Case Management
Long Term Care
Managed Care
KDHE (KanCare)
KDADs (KanCare)
All Other Medical
Total Expenditures

============================================================
FY2021
============================================================
Inpatient
Inpatient Hospital-DSH Adjustments
Mental Health Facilities-DSH Adjustments
Outpatient
Pharmacy
Professional Services
Medicare Buy-In
HCBS Waivers
Targeted Case Management
Long Term Care
Managed Care
KDHE (KanCare)
KDADs (KanCare)
All Other Medical
Total Expenditures

============================================================
FY2022
============================================================
Inpatient
Inpatient Hospital-DSH Adjustments
Mental Health Facilities-DSH Adjustments
Outpatient
Pharmacy
Professional Services
Medicare Buy-In
HCBS Waivers
Targeted Case Management
Long Term Care
Managed Care
KDHE (KanCare)
KDADs (KanCare)
All Other Medical
Total Expenditures

============================================================
FY2023
============================================================
Inpatient
Inpatient Hospital-DSH Adjustments
Mental Health Facilities-DSH Adjustments
Outpatient
Pharmacy
Professional Services
Medicare Buy-In
HCBS Waivers
Targeted Case Management
Long Term Care
Managed Care
KDHE (KanCare)
KDADs (KanCare)
All Other Medical
Total Expenditures

============================================================
FY2024
============================================================
Inpatient
Inpatient Hospital-DSH Adjustments
Mental Health Facilities-DSH Adjustments
Outpatient
Pharmacy
Professional Services
Medicare Buy-In
HCBS Waivers (Fee for Service Only)
Targeted Case Management
Long Term Care
Managed Care
KDHE (KanCare)
KDADs (KanCare)
All Other Medical
Total Expenditures

============================================================
FY2025
============================================================
Inpatient
Inpatient Hospital-DSH Adjustments
Mental Health Facilities-DSH Adjustments
Outpatient
Pharmacy
Professional Services
Medicare Buy-In
HCBS Waivers (Fee for Service Only)
Targeted Case Management
Long Term Care
Managed Care
KDHE (KanCare)
KDADs (KanCare)
All Other Medical
Total Expenditures

============================================================
FY2026
============================================================
Inpatient
Inpatient Hospital-DSH Adjustments
Mental Health Facilities-DSH Adjustments
Outpatient
Pharmacy
Professional Services
Medicare Buy-In
HCBS Waivers (Fee for Service Only)
Targeted Case Management
Long Term Care
Managed Care
KDHE (KanCare)
KDADs (KanCare)
All Other Medical
Total Expenditures

In [26]:
# ---------------------------------------------------------
# TEST CATEGORY-OF-SERVICE EXTRACTION — FY2018
# ---------------------------------------------------------

import re

# Define the FY2018 report.
pdf_path = Path("../data/raw/MAR FY 2018.pdf")

# Open page 10, which contains the Category of Service table.
with pdfplumber.open(pdf_path) as pdf:
    page_text = pdf.pages[9].extract_text() or ""

# Create an empty list where we'll store the extracted records.
category_records = []

# Examine the table one line at a time.
for line in page_text.splitlines():

    # Find every dollar amount in the row.
    #
    # This pattern also allows negative values such as -$1,000,
    # which can occur because Medicaid reports contain adjustments.
    dollar_values = re.findall(
        r"-?\$[\d,]+(?:\.\d+)?",
        line
    )

    # A normal category row contains:
    # 12 monthly values + Total + Monthly Average + State Funds.
    #
    # That means we expect 15 dollar values.
    if len(dollar_values) == 15:

        # Locate the first dollar sign so everything before it
        # can be treated as the category name.
        first_dollar = re.search(r"-?\$", line)

        category = line[:first_dollar.start()].strip()

        # The 13th monetary value (index 12) is the annual Total.
        annual_total_text = dollar_values[12]

        # Remove formatting characters so the value can
        # be stored as a numeric integer instead of text.
        annual_total = int(
            annual_total_text
            .replace("$", "")
            .replace(",", "")
        )

        # Store one clean record.
        category_records.append({
            "fiscal_year": 2018,
            "category": category,
            "annual_expenditures": annual_total
        })

# Convert the extracted records into a DataFrame.
fy2018_categories = pd.DataFrame(category_records)

fy2018_categories

    fiscal_year                                 category  annual_expenditures
0          2018                                Inpatient            112060345
1          2018       Inpatient Hospital-DSH Adjustments             60533406
2          2018  Mental Health Facilities-DSH Adjustment             27670993
3          2018                               Outpatient              4687401
4          2018                                 Pharmacy             12153276
5          2018                    Professional Services             47490970
6          2018                          Medicare Buy-In            108145250
7          2018                             HCBS Waivers                60749
8          2018                 Targeted Case Management               610987
9          2018                           Long Term Care             76511276
10         2018                             Managed Care           3213313409
11         2018                           KDHE (KanCare)           1778227556
12         2018                          KDADs (KanCare)           1417490410
13         2018                        All Other Medical              3621017
14         2018                       Total Expenditures           3666859079

In [27]:
# ---------------------------------------------------------
# FUNCTION: EXTRACT CATEGORY-OF-SERVICE ANNUAL TOTALS
# ---------------------------------------------------------

def extract_category_expenditures(pdf_path, fiscal_year):
    """
    Extract annual Category of Service expenditure totals
    from Kansas Medicaid reports using the FY2018-FY2026 format.
    """

    # Open the Medicaid report.
    with pdfplumber.open(pdf_path) as pdf:

        # Page 10 contains the Category of Service table
        # for FY2018-FY2026.
        page_text = pdf.pages[9].extract_text() or ""

    # Store the extracted category records here.
    records = []

    # Process the table one line at a time.
    for line in page_text.splitlines():

        # Extract all monetary values from the current row.
        # Negative values are allowed because some report
        # categories contain accounting adjustments.
        dollar_values = re.findall(
            r"-?\$[\d,]+(?:\.\d+)?",
            line
        )

        # A complete category row should contain:
        # 12 months + Total + Average + State Funds = 15 values.
        if len(dollar_values) == 15:

            # Find where the first monetary value begins.
            first_dollar = re.search(r"-?\$", line)

            # Everything before the first dollar value
            # represents the category name.
            category = line[:first_dollar.start()].strip()

            # Index 12 is the annual Total column.
            annual_total_text = dollar_values[12]

            # Convert the formatted dollar string into an integer.
            # Example: "$1,234,567" becomes 1234567.
            annual_total = int(
                annual_total_text
                .replace("$", "")
                .replace(",", "")
            )

            # Add the clean record to our results.
            records.append({
                "fiscal_year": fiscal_year,
                "category": category,
                "annual_expenditures": annual_total
            })

    # Return the extracted records as a DataFrame.
    return pd.DataFrame(records)

In [28]:
# ---------------------------------------------------------
# EXTRACT CATEGORY DATA FOR FY2018-FY2026
# ---------------------------------------------------------

# Store each fiscal year's extracted DataFrame.
all_category_years = []

for fiscal_year in range(2018, 2027):

    # Construct the appropriate PDF filename automatically.
    pdf_path = Path(
        f"../data/raw/MAR FY {fiscal_year}.pdf"
    )

    # Extract this year's category expenditures.
    yearly_categories = extract_category_expenditures(
        pdf_path,
        fiscal_year
    )

    # Store it for later combination.
    all_category_years.append(yearly_categories)

    # Print the number of rows extracted as a quick
    # structural check for each fiscal year.
    print(
        f"FY{fiscal_year}: "
        f"{len(yearly_categories)} rows extracted"
    )

# Combine all nine fiscal years into one dataset.
category_df = pd.concat(
    all_category_years,
    ignore_index=True
)

print("\nCombined shape:", category_df.shape)

FY2018: 15 rows extracted
FY2019: 15 rows extracted
FY2020: 15 rows extracted
FY2021: 15 rows extracted
FY2022: 15 rows extracted
FY2023: 15 rows extracted
FY2024: 15 rows extracted
FY2025: 15 rows extracted
FY2026: 15 rows extracted

Combined shape: (135, 3)

In [29]:
# ---------------------------------------------------------
# VALIDATE CATEGORY-OF-SERVICE TOTALS
# ---------------------------------------------------------

# Select only the "Total Expenditures" row from each fiscal year.
# This gives us the annual total reported on the
# Category of Service page.
category_totals = (
    category_df[
        category_df["category"] == "Total Expenditures"
    ][
        ["fiscal_year", "annual_expenditures"]
    ]
    .rename(
        columns={
            "annual_expenditures": "category_report_total"
        }
    )
)

# Get the annual totals that we previously calculated
# from the monthly Beneficiaries and Expenditures data.
existing_totals = annual_summary[
    ["fiscal_year", "total_expenditures"]
].copy()

# Compare only FY2018-FY2026 because category_df
# begins in FY2018.
validation_df = category_totals.merge(
    existing_totals,
    on="fiscal_year",
    how="left"
)

# Calculate the difference between the two independently
# extracted annual totals.
#
# A difference of 0 means the two report sections agree exactly.
validation_df["difference"] = (
    validation_df["category_report_total"]
    - validation_df["total_expenditures"]
)

validation_df

   fiscal_year  category_report_total  total_expenditures  difference
0         2018             3666859079          3666859078           1
1         2019             3936843520          3936843520           0
2         2020             4189753837          4189753837           0
3         2021             4426412759          4426412757           2
4         2022             4859228793          4859228793           0
5         2023             5429434408          5429434410          -2
6         2024             5510409877          5510409877           0
7         2025             5955636293          5955636294          -1
8         2026             5848965316          5848965317          -1

In [30]:
# ---------------------------------------------------------
# STANDARDIZE CATEGORY NAMES
# ---------------------------------------------------------

# Create a copy so we preserve the original extracted data.
category_clean_df = category_df.copy()

# Standardize only the category labels that we identified
# as inconsistent across fiscal years.
category_name_map = {
    "Mental Health Facilities-DSH Adjustment":
        "Mental Health Facilities-DSH Adjustments",

    "HCBS Waivers (Fee for Service Only)":
        "HCBS Waivers"
}

# Replace the inconsistent labels with standardized names.
category_clean_df["category"] = (
    category_clean_df["category"]
    .replace(category_name_map)
)

# Check that every fiscal year now contains
# the same standardized set of categories.
category_check = (
    category_clean_df
    .groupby("fiscal_year")["category"]
    .nunique()
)

print(category_check)

fiscal_year
2018    15
2019    15
2020    15
2021    15
2022    15
2023    15
2024    15
2025    15
2026    15
Name: category, dtype: int64

In [31]:
# ---------------------------------------------------------
# COMPARE CATEGORY EXPENDITURES: FY2023 VS FY2026
# ---------------------------------------------------------

# Keep the categories that represent actual expenditure categories.
#
# We exclude:
# - Total Expenditures because it is the overall total, not a category.
# - KDHE and KDADS KanCare because they are components of Managed Care.
#   Including them alongside Managed Care would double-count spending.
analysis_categories = category_clean_df[
    ~category_clean_df["category"].isin([
        "Total Expenditures",
        "KDHE (KanCare)",
        "KDADs (KanCare)"
    ])
].copy()

# Select FY2023 as our starting point.
fy2023 = (
    analysis_categories[
        analysis_categories["fiscal_year"] == 2023
    ][["category", "annual_expenditures"]]
    .rename(
        columns={
            "annual_expenditures": "fy2023_expenditures"
        }
    )
)

# Select FY2026 as our ending point.
fy2026 = (
    analysis_categories[
        analysis_categories["fiscal_year"] == 2026
    ][["category", "annual_expenditures"]]
    .rename(
        columns={
            "annual_expenditures": "fy2026_expenditures"
        }
    )
)

# Match the same categories between the two fiscal years.
category_change = fy2023.merge(
    fy2026,
    on="category",
    how="inner"
)

# Calculate the absolute dollar change.
category_change["dollar_change"] = (
    category_change["fy2026_expenditures"]
    - category_change["fy2023_expenditures"]
)

# Calculate percentage change.
#
# We use .where() to avoid dividing by zero if a category
# happened to have no expenditures in FY2023.
category_change["percent_change"] = (
    (
        category_change["dollar_change"]
        / category_change["fy2023_expenditures"]
    ) * 100
).where(
    category_change["fy2023_expenditures"] != 0
)

# Sort from the largest increase to the largest decrease.
category_change = category_change.sort_values(
    "dollar_change",
    ascending=False
).reset_index(drop=True)

category_change

,category,fy2023_expenditures,fy2026_expenditures,dollar_change,percent_change
0,Managed Care,4896716326,5415182932,518466606,10.588047
1,Medicare Buy-In,160899888,178829330,17929442,11.143228
2,Pharmacy,18028527,28138994,10110467,56.080383
3,Long Term Care,81133903,88769206,7635303,9.410743
4,Outpatient,2052692,3806784,1754092,85.453249
5,All Other Medical,2292883,3036089,743206,32.413603
6,Targeted Case Management,988519,1375357,386838,39.133087
7,HCBS Waivers,7843,26322,18479,235.611373
8,Professional Services,52789999,51546859,-1243140,-2.354878
9,Mental Health Facilities-DSH Adjustments,15511332,8789169,-6722163,-43.337110
10,Inpatient Hospital-DSH Adjustments,75103746,33830313,-41273433,-54.955226
11,Inpatient,123908751,35633962,-88274789,-71.241771

In [32]:
# ---------------------------------------------------------
# SAVE CLEAN CATEGORY EXPENDITURE DATA
# ---------------------------------------------------------

# Define where the processed category dataset will be stored.
category_output_path = Path(
    "../data/processed/kansas_medicaid_category_expenditures_2018_2026.csv"
)

# Save the standardized category data.
#
# We keep all 15 rows, including Total Expenditures,
# KDHE (KanCare), and KDADS (KanCare), because preserving
# the complete extracted dataset is useful.
#
# We will exclude subtotal/component rows only when
# performing analyses where they could cause double-counting.
category_clean_df.to_csv(
    category_output_path,
    index=False
)

# Confirm that the file was successfully created.
print("Saved:", category_output_path.exists())
print("Location:", category_output_path)
print("Rows:", len(category_clean_df))

Saved: True
Location: ../data/processed/kansas_medicaid_category_expenditures_2018_2026.csv
Rows: 135